# Generated by Django 3.2.7 on 2021-09-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='smalldescription',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
