# Generated by Django 3.2.7 on 2021-09-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_smalldescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='smalldescription',
            field=models.TextField(default=None),
        ),
    ]
