# Generated by Django 3.2.6 on 2021-08-27 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name2',
            new_name='name',
        ),
    ]
